spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library-test
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
#    show-sql: true
    hibernate:
      #format_sql: true
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB


itemImgLocation: C:/library/book
uploadPath: file:///C:/library/

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucket: storage-ehs-integration-01
      dir: library/storage/dev/book/
    region:
      static: ap-northeast-2
    stack:
      auto: false