logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.may.mybatispractice.dto

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
---

spring:
  profiles:
    active: dev

---

spring:
  profiles:
    active: real

---

spring:
  profiles:
    active: test